% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  10pt,
  letterpaper,
]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{neurips_2025}
\usepackage{booktabs}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{nicefrac}
\usepackage{microtype}
\usepackage{xcolor}
\usepackage{graphicx}
\usepackage{subcaption}
\usepackage{multirow}
\usepackage{enumitem}
% Custom commands
\newcommand{\pcoop}{P(\text{C})}
\newcommand{\pcoopgiven}[1]{P(\text{C} \mid #1)}
\newcommand{\pp}{\text{\,pp}}
\newcommand{\fhat}{\hat{f}}
\newcommand{\commgap}{\Delta_{\text{comm}}}
\newcommand{\tablabel}[1]{\label{tab:#1}}
\setmainfont{texgyretermes-regular.otf}[
  Path=/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/,
  BoldFont=texgyretermes-bold.otf,
  ItalicFont=texgyretermes-italic.otf,
  BoldItalicFont=texgyretermes-bolditalic.otf
]
\setsansfont{texgyreheros-regular.otf}[
  Path=/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/,
  BoldFont=texgyreheros-bold.otf,
  ItalicFont=texgyreheros-italic.otf,
  BoldItalicFont=texgyreheros-bolditalic.otf
]
\setmonofont{texgyrecursor-regular.otf}[
  Path=/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre/,
  BoldFont=texgyrecursor-bold.otf,
  ItalicFont=texgyrecursor-italic.otf,
  BoldItalicFont=texgyrecursor-bolditalic.otf
]
\setmathfont{texgyretermes-math.otf}[
  Path=/usr/local/texlive/2024/texmf-dist/fonts/opentype/public/tex-gyre-math/
]
\makeatletter
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{plainnat}
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Same-Checkpoint Controls for Disentangling Communication Benefit from Learning Dynamics in Multi-Agent Reinforcement Learning},
  pdfauthor={Anonymous Authors},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

% Quarto template partial: NeurIPS title block
% Suppresses default Quarto author rendering; uses NeurIPS \maketitle
\title{Same-Checkpoint Controls for Disentangling Communication Benefit
from Learning Dynamics in Multi-Agent Reinforcement Learning}

\author{%
  Anonymous Authors \\
  % Author information omitted for double-blind review
}
\begin{document}
\maketitle
% Auto-generated by paper_data.py — do not edit manually
% Run: python paper_data.py --gen-defs

% Table 1: comm vs no-comm cooperation rates
\def\TIcommTFFk{0.775 \pm 0.028}  % comm f=3.500 50k
\def\TIncTFFk{0.472 \pm 0.012}  % no_comm f=3.500 50k
\def\TIgapTFFk{\mathbf{+0.303}}  % gap f=3.500 50k  p=0.0001
\def\TIcommTFHk{0.559 \pm 0.055}  % comm f=3.500 100k
\def\TIncTFHk{0.421 \pm 0.023}  % no_comm f=3.500 100k
\def\TIgapTFHk{+0.137}  % gap f=3.500 100k  p=0.0279
\def\TIcommTFOfk{0.536 \pm 0.038}  % comm f=3.500 150k
\def\TIncTFOfk{0.450 \pm 0.025}  % no_comm f=3.500 150k
\def\TIgapTFOfk{+0.086}  % gap f=3.500 150k  p=0.0609
\def\TIcommFVFk{0.761 \pm 0.032}  % comm f=5.000 50k
\def\TIncFVFk{0.732 \pm 0.038}  % no_comm f=5.000 50k
\def\TIgapFVFk{+0.029}  % gap f=5.000 50k  p=0.5427
\def\TIcommFVHk{0.556 \pm 0.064}  % comm f=5.000 100k
\def\TIncFVHk{0.649 \pm 0.042}  % no_comm f=5.000 100k
\def\TIgapFVHk{-0.093}  % gap f=5.000 100k  p=0.2766
\def\TIcommFVOfk{0.561 \pm 0.041}  % comm f=5.000 150k
\def\TIncFVOfk{0.800 \pm 0.032}  % no_comm f=5.000 150k
\def\TIgapFVOfk{-0.240}  % gap f=5.000 150k  p=0.0009

% Table 2: channel controls at 50k
\def\TIILearned{0.809}  % learned (n=5)
\def\TIIIndep{0.669}  % indep_random (n=3)
\def\TIIZero{0.641}  % always_zero (n=3)
\def\TIIPub{0.620}  % public_random (n=3)

% Table 3: continuation controls
\def\TIIInSeeds{15}  % number of seeds
\def\TIIIsource{same-checkpoint}  % data source type
\def\TIIIpending{}  % pending note
\def\TIIILearnedFk{0.775 \pm 0.028}  % learned 50k f=3.5
\def\TIIILearnedHk{0.559 \pm 0.055}  % learned 100k f=3.5
\def\TIIILearnedOfk{0.536 \pm 0.038}  % learned 150k f=3.5
\def\TIIILearnedFkFV{0.761 \pm 0.032}  % learned 50k f=5.0
\def\TIIILearnedOfkFV{0.561 \pm 0.041}  % learned 150k f=5.0
\def\TIIIIndepFk{0.775 \pm 0.028}  % indep_random 50k f=3.5
\def\TIIIIndepHk{0.459 \pm 0.028}  % indep_random 100k f=3.5
\def\TIIIIndepOfk{0.415 \pm 0.019}  % indep_random 150k f=3.5
\def\TIIIIndepFkFV{0.761 \pm 0.032}  % indep_random 50k f=5.0
\def\TIIIIndepOfkFV{0.631 \pm 0.044}  % indep_random 150k f=5.0
\def\TIIIIndepGapOfk{+12.1}  % learned - indep_random gap at 150k (pp)
\def\TIIIIndepGapOfkCI{[+3.4,\,+21.5]}  % 95% CI for gap (pp)
\def\TIIIIndepGapOfkP{=0.0189}  % p-value for gap
\def\TIIIPubFk{0.775 \pm 0.028}  % public_random 50k f=3.5
\def\TIIIPubHk{0.425 \pm 0.052}  % public_random 100k f=3.5
\def\TIIIPubOfk{0.399 \pm 0.022}  % public_random 150k f=3.5
\def\TIIIPubFkFV{0.761 \pm 0.032}  % public_random 50k f=5.0
\def\TIIIPubOfkFV{0.614 \pm 0.031}  % public_random 150k f=5.0
\def\TIIIPubGapOfk{+13.7}  % learned - public_random gap at 150k (pp)
\def\TIIIPubGapOfkCI{[+5.7,\,+21.5]}  % 95% CI for gap (pp)
\def\TIIIPubGapOfkP{=0.0072}  % p-value for gap
\def\TIIIZeroFk{0.775 \pm 0.028}  % always_zero 50k f=3.5
\def\TIIIZeroHk{0.343 \pm 0.048}  % always_zero 100k f=3.5
\def\TIIIZeroOfk{0.342 \pm 0.036}  % always_zero 150k f=3.5
\def\TIIIZeroFkFV{0.761 \pm 0.032}  % always_zero 50k f=5.0
\def\TIIIZeroOfkFV{0.544 \pm 0.043}  % always_zero 150k f=5.0
\def\TIIIZeroGapOfk{+19.4}  % learned - always_zero gap at 150k (pp)
\def\TIIIZeroGapOfkCI{[+11.3,\,+29.2]}  % 95% CI for gap (pp)
\def\TIIIZeroGapOfkP{=0.0002}  % p-value for gap

% Same-checkpoint sender-shuffle continuation (matched-stat control)
\def\TSSshufCoopTFOfk{0.446}  % sender-shuffle coop f=3.5 150k
\def\TSSshufCoopTFOfkSEM{0.028}  % sender-shuffle coop f=3.5 150k SEM
\def\TSSshufCoopTFOfkPM{0.446 \pm 0.028}  % sender-shuffle coop f=3.5 150k mean ± SEM
\def\TSSgapTFOfk{+9.0}  % learned - shuffle gap f=3.5 150k (pp)
\def\TSSgapTFOfkCI{[-1.0,\,+18.7]}  % 95% CI for gap f=3.5 150k (pp)
\def\TSSgapTFOfkSign{9/15}  % seeds favoring learned at f=3.5 150k
\def\TSSshufCoopFVOfk{0.720}  % sender-shuffle coop f=5.0 150k
\def\TSSshufCoopFVOfkSEM{0.038}  % sender-shuffle coop f=5.0 150k SEM
\def\TSSshufCoopFVOfkPM{0.720 \pm 0.038}  % sender-shuffle coop f=5.0 150k mean ± SEM
\def\TSSgapFVOfk{-15.9}  % learned - shuffle gap f=5.0 150k (pp)
\def\TSSgapFVOfkCI{[-29.4,\,-3.4]}  % 95% CI for gap f=5.0 150k (pp)
\def\TSSgapFVOfkSign{6/15}  % seeds favoring learned at f=5.0 150k
\def\TIIIminOfk{0.342}  % min 150k across modes
\def\TIIImaxOfk{0.536}  % max 150k across modes

% Table 4: frozen-checkpoint interventions
\def\TFRZerosFk{+0.0}  % zeros 50k (pp)
\def\TFRZerosOfk{+6.1}  % zeros 150k (pp)
\def\TFRZerosFkSEM{2.4}  % zeros 50k SEM (pp)
\def\TFRZerosOfkSEM{4.2}  % zeros 150k SEM (pp)
\def\TFRZerosOfkCI{[-1.2,\,+14.5]}  % zeros 150k 95% CI (pp)
\def\TFRZerosOfkP{=0.1667}  % zeros 150k p-value
\def\TFRZerosOfkSign{9/15}  % zeros 150k seeds with natural > intervention
\def\TFRFixZeroFk{-2.2}  % fixed0 50k (pp)
\def\TFRFixZeroOfk{+3.0}  % fixed0 150k (pp)
\def\TFRFixZeroFkSEM{3.2}  % fixed0 50k SEM (pp)
\def\TFRFixZeroOfkSEM{3.2}  % fixed0 150k SEM (pp)
\def\TFRFixZeroOfkCI{[-3.1,\,+8.8]}  % fixed0 150k 95% CI (pp)
\def\TFRFixZeroOfkP{=0.3494}  % fixed0 150k p-value
\def\TFRFixZeroOfkSign{9/15}  % fixed0 150k seeds with natural > intervention
\def\TFRPubFk{-2.0}  % public_random 50k (pp)
\def\TFRPubOfk{+1.6}  % public_random 150k (pp)
\def\TFRPubFkSEM{1.5}  % public_random 50k SEM (pp)
\def\TFRPubOfkSEM{1.6}  % public_random 150k SEM (pp)
\def\TFRPubOfkCI{[-1.3,\,+4.8]}  % public_random 150k 95% CI (pp)
\def\TFRPubOfkP{=0.3741}  % public_random 150k p-value
\def\TFRPubOfkSign{7/15}  % public_random 150k seeds with natural > intervention
\def\TFRIndepFk{-0.3}  % indep_random 50k (pp)
\def\TFRIndepOfk{+1.6}  % indep_random 150k (pp)
\def\TFRIndepFkSEM{0.7}  % indep_random 50k SEM (pp)
\def\TFRIndepOfkSEM{0.7}  % indep_random 150k SEM (pp)
\def\TFRIndepOfkCI{[+0.4,\,+3.0]}  % indep_random 150k 95% CI (pp)
\def\TFRIndepOfkP{=0.0286}  % indep_random 150k p-value
\def\TFRIndepOfkSign{10/15}  % indep_random 150k seeds with natural > intervention
\def\TFRShuffleFk{-2.9}  % sender_shuffle 50k (pp)
\def\TFRShuffleOfk{-3.2}  % sender_shuffle 150k (pp)
\def\TFRShuffleFkSEM{0.9}  % sender_shuffle 50k SEM (pp)
\def\TFRShuffleOfkSEM{0.6}  % sender_shuffle 150k SEM (pp)
\def\TFRShuffleOfkCI{[-4.4,\,-2.3]}  % sender_shuffle 150k 95% CI (pp)
\def\TFRShuffleOfkP{<0.0001}  % sender_shuffle 150k p-value
\def\TFRShuffleOfkSign{0/15}  % sender_shuffle 150k seeds with natural > intervention
\def\TFRPermuteFk{-0.4}  % permute_slots 50k (pp)
\def\TFRPermuteOfk{+1.6}  % permute_slots 150k (pp)
\def\TFRPermuteFkSEM{0.5}  % permute_slots 50k SEM (pp)
\def\TFRPermuteOfkSEM{0.7}  % permute_slots 150k SEM (pp)
\def\TFRPermuteOfkCI{[+0.3,\,+3.1]}  % permute_slots 150k 95% CI (pp)
\def\TFRPermuteOfkP{=0.0461}  % permute_slots 150k p-value
\def\TFRPermuteOfkSign{11/15}  % permute_slots 150k seeds with natural > intervention

% Table 5: endpoint sender-causal probe
\def\TSCDeltaZeroFive{-0.0}  % sender-causal mean delta at f=0.5 (pp)
\def\TSCDeltaZeroFiveCI{[-0.0,\,+0.0]}  % sender-causal mean delta CI at f=0.5 (pp)
\def\TSCAbsZeroFive{0.1}  % sender-causal mean abs delta at f=0.5 (pp)
\def\TSCAbsZeroFiveCI{[+0.1,\,+0.2]}  % sender-causal mean abs delta CI at f=0.5 (pp)
\def\TSCFlipZeroZeroFive{0.1}  % sender-causal flip0 at f=0.5 (%)
\def\TSCFlipOneZeroFive{0.1}  % sender-causal flip1 at f=0.5 (%)
\def\TSCDeltaOneFive{-0.0}  % sender-causal mean delta at f=1.5 (pp)
\def\TSCDeltaOneFiveCI{[-0.3,\,+0.3]}  % sender-causal mean delta CI at f=1.5 (pp)
\def\TSCAbsOneFive{0.9}  % sender-causal mean abs delta at f=1.5 (pp)
\def\TSCAbsOneFiveCI{[+0.6,\,+1.3]}  % sender-causal mean abs delta CI at f=1.5 (pp)
\def\TSCFlipZeroOneFive{0.7}  % sender-causal flip0 at f=1.5 (%)
\def\TSCFlipOneOneFive{0.6}  % sender-causal flip1 at f=1.5 (%)
\def\TSCDeltaTwoFive{-0.7}  % sender-causal mean delta at f=2.5 (pp)
\def\TSCDeltaTwoFiveCI{[-2.6,\,+1.2]}  % sender-causal mean delta CI at f=2.5 (pp)
\def\TSCAbsTwoFive{7.7}  % sender-causal mean abs delta at f=2.5 (pp)
\def\TSCAbsTwoFiveCI{[+6.4,\,+9.3]}  % sender-causal mean abs delta CI at f=2.5 (pp)
\def\TSCFlipZeroTwoFive{7.3}  % sender-causal flip0 at f=2.5 (%)
\def\TSCFlipOneTwoFive{6.9}  % sender-causal flip1 at f=2.5 (%)
\def\TSCDeltaThreeFive{+0.3}  % sender-causal mean delta at f=3.5 (pp)
\def\TSCDeltaThreeFiveCI{[-0.4,\,+1.0]}  % sender-causal mean delta CI at f=3.5 (pp)
\def\TSCAbsThreeFive{5.0}  % sender-causal mean abs delta at f=3.5 (pp)
\def\TSCAbsThreeFiveCI{[+4.1,\,+5.9]}  % sender-causal mean abs delta CI at f=3.5 (pp)
\def\TSCFlipZeroThreeFive{12.2}  % sender-causal flip0 at f=3.5 (%)
\def\TSCFlipOneThreeFive{12.9}  % sender-causal flip1 at f=3.5 (%)
\def\TSCDeltaFiveZero{+0.4}  % sender-causal mean delta at f=5.0 (pp)
\def\TSCDeltaFiveZeroCI{[-0.5,\,+1.1]}  % sender-causal mean delta CI at f=5.0 (pp)
\def\TSCAbsFiveZero{3.8}  % sender-causal mean abs delta at f=5.0 (pp)
\def\TSCAbsFiveZeroCI{[+3.2,\,+4.3]}  % sender-causal mean abs delta CI at f=5.0 (pp)
\def\TSCFlipZeroFiveZero{9.8}  % sender-causal flip0 at f=5.0 (%)
\def\TSCFlipOneFiveZero{11.5}  % sender-causal flip1 at f=5.0 (%)
\def\TSCAbsSelfZeroFive{0.1}  % overall_self sender-causal mean abs delta at f=0.5 (pp)
\def\TSCAbsSelfOneFive{1.0}  % overall_self sender-causal mean abs delta at f=1.5 (pp)
\def\TSCAbsSelfTwoFive{8.1}  % overall_self sender-causal mean abs delta at f=2.5 (pp)
\def\TSCAbsSelfThreeFive{5.7}  % overall_self sender-causal mean abs delta at f=3.5 (pp)
\def\TSCAbsSelfFiveZero{4.0}  % overall_self sender-causal mean abs delta at f=5.0 (pp)
\def\TSCAbsNonselfZeroFive{0.1}  % overall_nonself sender-causal mean abs delta at f=0.5 (pp)
\def\TSCAbsNonselfOneFive{0.9}  % overall_nonself sender-causal mean abs delta at f=1.5 (pp)
\def\TSCAbsNonselfTwoFive{7.7}  % overall_nonself sender-causal mean abs delta at f=2.5 (pp)
\def\TSCAbsNonselfThreeFive{5.0}  % overall_nonself sender-causal mean abs delta at f=3.5 (pp)
\def\TSCAbsNonselfFiveZero{3.8}  % overall_nonself sender-causal mean abs delta at f=5.0 (pp)

% Table 6: mute experiment
\def\TIVcommCoop{0.536}  % comm coop at 150k
\def\TIVcommWelf{37.43}  % comm welfare
\def\TIVncCoop{0.450}  % no-comm coop at 150k
\def\TIVncWelf{34.01}  % no-comm welfare
\def\TIVmuteCoop{0.367}  % mute coop at 150k
\def\TIVmuteWelf{30.69}  % mute welfare
\def\TIVmuteCoopPct{36.7}  % mute coop %
\def\TIVncCoopPct{45.0}  % no-comm coop %

% Table 7: aggregate vs per-sender token effects
\def\TVaggFk{-0.000}  % aggregate 50k
\def\TVaggFkCI{[-0.028,\,+0.025]}  % aggregate 50k CI
\def\TVpsFk{0.218}  % per-sender 50k
\def\TVpsFkCI{[+0.198,\,+0.238]}  % per-sender 50k CI
\def\TVratioFk{---}  % ratio 50k (agg~0)
\def\TVaggHk{-0.008}  % aggregate 100k
\def\TVaggHkCI{[-0.019,\,+0.004]}  % aggregate 100k CI
\def\TVpsHk{0.178}  % per-sender 100k
\def\TVpsHkCI{[+0.156,\,+0.200]}  % per-sender 100k CI
\def\TVratioHk{23.3\times}  % ratio 100k
\def\TVaggOfk{0.003}  % aggregate 150k
\def\TVaggOfkCI{[-0.012,\,+0.019]}  % aggregate 150k CI
\def\TVpsOfk{0.186}  % per-sender 150k
\def\TVpsOfkCI{[+0.166,\,+0.206]}  % per-sender 150k CI
\def\TVratioOfk{---}  % ratio 150k (agg~0)

% Table 8: polarity alignment (summary over 15 seeds)
\def\TVInSeeds{15}  % number of seeds in alignment table
\def\TVItrajAchievedfull{2}  % n seeds with trajectory 'Achieved full alignment'
\def\TVItrajImproved{3}  % n seeds with trajectory 'Improved'
\def\TVItrajLostalignmen{5}  % n seeds with trajectory 'Lost alignment'
\def\TVItrajPolarityflip{2}  % n seeds with trajectory 'Polarity flipped'
\def\TVItrajStable{3}  % n seeds with trajectory 'Stable'

% Prose claims
\def\pvGapTFFkPP{30.3}  % comm gap f=3.5 50k (pp)
\def\pvGapTFOfkPP{8.6}  % comm gap f=3.5 150k (pp)
\def\pvGapTFFkPval{=0.0001}  % p-value for gap at f=3.5 50k
\def\pvGapDeclinePct{72}  % gap decline %
\def\pvGapRangeLo{10.5}  % per-seed gap min at 50k (pp)
\def\pvGapRangeHi{49.4}  % per-seed gap max at 50k (pp)
\def\pvNposOfk{10}  % n seeds with positive gap at 150k
\def\pvGapFVFkPP{2.9}  % comm gap f=5.0 50k (pp)
\def\pvGapFVOfkPP{-24.0}  % comm gap f=5.0 150k (pp)
\def\pvCtrlAdvLo{14}  % control advantage low (pp)
\def\pvCtrlAdvHi{19}  % control advantage high (pp)
\def\pvMuteBelowPP{8}  % mute below no-comm (pp)
\def\pvRatioFk{>44}  % per-sender/agg ratio 50k
\def\pvRatioOfk{---}  % per-sender/agg ratio 150k
\def\pvAggFkPP{-0.0}  % aggregate token effect 50k (pp)
\def\pvPsFkPP{21.8}  % per-sender effect 50k (pp)
\def\pvAggOfkPP{0.3}  % aggregate effect 150k (pp)
\def\pvPsOfkPP{18.6}  % per-sender effect 150k (pp)
\def\pvCommCoopTFFkPct{77.5}  % comm coop % at f=3.5 50k
\def\pvNcCoopTFFkPct{47}  % no-comm coop % at f=3.5 50k
\def\pvNSeeds{15}  % total number of seeds

% Appendix: summary stats for cooperation and gaps at f=3.5
\def\pvPSnSeedsFk{15}  % n seeds at 50k
\def\pvPScommMeanFk{0.775}  % mean comm 3.5 50k
\def\pvPScommSDFk{0.108}  % SD comm 3.5 50k
\def\pvPScommMinFk{0.544}  % min comm 3.5 50k
\def\pvPScommMaxFk{0.904}  % max comm 3.5 50k
\def\pvPSgapMeanFk{+0.303}  % mean gap 3.5 50k
\def\pvPSgapSDFk{0.094}  % SD gap 3.5 50k
\def\pvPSgapMinFk{+0.105}  % min gap 3.5 50k
\def\pvPSgapMaxFk{+0.494}  % max gap 3.5 50k
\def\pvPSnSeedsHk{15}  % n seeds at 100k
\def\pvPScommMeanHk{0.559}  % mean comm 3.5 100k
\def\pvPScommSDHk{0.211}  % SD comm 3.5 100k
\def\pvPScommMinHk{0.219}  % min comm 3.5 100k
\def\pvPScommMaxHk{0.919}  % max comm 3.5 100k
\def\pvPSgapMeanHk{+0.137}  % mean gap 3.5 100k
\def\pvPSgapSDHk{0.218}  % SD gap 3.5 100k
\def\pvPSgapMinHk{-0.233}  % min gap 3.5 100k
\def\pvPSgapMaxHk{+0.544}  % max gap 3.5 100k
\def\pvPSnSeedsOfk{15}  % n seeds at 150k
\def\pvPScommMeanOfk{0.536}  % mean comm 3.5 150k
\def\pvPScommSDOfk{0.146}  % SD comm 3.5 150k
\def\pvPScommMinOfk{0.325}  % min comm 3.5 150k
\def\pvPScommMaxOfk{0.890}  % max comm 3.5 150k
\def\pvPSgapMeanOfk{+0.086}  % mean gap 3.5 150k
\def\pvPSgapSDOfk{0.162}  % SD gap 3.5 150k
\def\pvPSgapMinOfk{-0.167}  % min gap 3.5 150k
\def\pvPSgapMaxOfk{+0.363}  % max gap 3.5 150k


\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[interior hidden, borderline west={3pt}{0pt}{shadecolor}, breakable, boxrule=0pt, enhanced, sharp corners, frame hidden]}{\end{tcolorbox}}\fi

\begin{abstract}
Emergent communication in multi-agent reinforcement learning is often evaluated with endpoint metrics such as cooperation, mutual information, or message--action correlations measured at the final checkpoint. Under independent decentralized learning, however, such metrics can conflate two distinct questions: whether message content shaped the training trajectory, and whether the frozen endpoint policy uses the online message stream as a robust, sender-consistent, and behaviorally useful code. We introduce \emph{same-checkpoint continuation controls} to probe these questions more directly: identical learned checkpoints are forked into learned, random, and silent channel modes, and their downstream outcomes are compared during continued training. As a case study, we apply this design to a four-agent extended public goods game with hidden regime switching and noisy private observations (15 seeds). Same-checkpoint controls show that learned messages retain a clear continued-learning advantage over silence and simple random channels in the mixed-motive regime, outperforming them by roughly 12--19 percentage points. A matched-stat sender-shuffle continuation control shrinks that advantage and its confidence interval overlaps zero, suggesting a mixture of genuine state-linked message value and broader channel dependence. In the cooperation-dominant regime, learned message content shows no corresponding advantage, and sender-shuffle can outperform learned communication. Complementary frozen-checkpoint interventions show that this training-time benefit does not translate into a robust endpoint protocol: sender-shuffled messages outperform natural messages, and sender-specific causal probes reveal sizable local effects that cancel in aggregate. These results show that communication benefit and learning dynamics can be more cleanly distinguished, and that continued-learning value and endpoint protocol coherence can come apart in ways that endpoint-only evaluation misses.
\end{abstract}

\hypertarget{sec-intro}{%
\section{Introduction}\label{sec-intro}}

Multi-agent reinforcement learning (MARL) has produced a growing body of
work on emergent communication, in which agents learn to use a discrete
signaling channel to coordinate behavior
\citep{foerster2016learning, sukhbaatar2016learning, lazaridou2017multi, havrylov2017emergence, mordatch2018emergence}.
For a comprehensive survey, see \citet{lazaridou2020emergent}. Beyond
classic sender--receiver benchmarks, communication is now studied in
broader cooperative settings, including sequential social dilemmas,
intention-sharing architectures, and zero-shot convention formation
\citep{leibo2017multi, kim2021communication, hu2020other, bullard2021quasi}.
A central question is whether agents develop meaningful, shared
communication protocols or merely learn policies that happen to
correlate with message-sending behavior
\citep{kottur2017natural, cao2018emergent}. Standard evaluation practice
therefore focuses on \emph{endpoint metrics}: mutual information (MI)
between messages and task-relevant variables \citep{lowe2019pitfalls},
topographic similarity \citep{lazaridou2017multi}, cooperation rates
measured at the final checkpoint, or positive-listening /
social-influence style diagnostics
\citep{eccles2019biases, jaques2019social}.

This attribution problem is especially acute under independent learning,
where non-stationarity makes it difficult to separate message semantics
from the broader training dynamics
\citep{papoudakis2019dealing, oroojlooyjadid2022review}. We study it in
a four-agent extended public goods game (EPGG) with hidden regime
switching, noisy private observations, and optional binary communication
\citep{orzan2024pgg}. The EPGG is a case study for this measurement
problem rather than the contribution by itself: it gives a setting with
fixed teams, sender-indexed message slots, feed-forward policies, and
mixed incentives in which endpoint-only evaluation is especially likely
to mislead.

Closest in spirit to our framing are critique papers that show standard
emergent-communication metrics can overstate semantics. Most notably,
\citet{lowe2019pitfalls} demonstrated a false-positive failure mode:
messages can appear informative under endpoint analyses while exerting
little or no causal influence on behavior. More recently, work on Lewis
games has shown that co-adaptation and overfitting can also degrade
protocol quality and generalization \citep{rita2022generalization}. Our
contribution is complementary to these critiques. We show the opposite
evaluation failure mode under independent learning: weak or brittle
endpoint use does not imply that messages were unimportant during
training, and same-checkpoint continuation controls provide a
constructive way to probe that split.

The setting sits at the intersection of several adjacent literatures.
Partially aligned signaling with hidden state is the core concern in
classic cheap-talk and strategic information transmission models
\citep{crawford1982strategic, chen2008selecting}. Communication in
public goods games also connects to experimental and institutional work
on cooperation under uncertainty
\citep{ledyard1995public, fehr2000cooperation, kosfeld2009institution, orzan2024pgg}.
More broadly, the paper fits within the Cooperative AI agenda of
understanding how decentralized agents and institutions can achieve
robust cooperation under imperfect alignment and limited information
\citep{dafoe2020open}.

We intentionally begin with independent learning rather than centralized
training. The goal is not to maximize coordination with the strongest
available training machinery, but to study a regime where attribution is
genuinely difficult: each agent learns under non-stationarity from local
observations and the message channel itself. In this setting,
improvements can easily be misread as endpoint semantics when they may
instead reflect broader co-learning dynamics. Independent PPO is
therefore a demanding but appropriate starting point for the evaluation
question we ask here.

We separate two questions that endpoint evaluation often collapses
together:

\begin{enumerate}[leftmargin=*,nosep]
  \item \textbf{Continued-learning value:} Does message \emph{content} change the downstream training trajectory when we hold the starting point fixed?
  \item \textbf{Endpoint protocol coherence:} Does the frozen final policy use the online message stream as a robust, sender-consistent, and behaviorally beneficial code?
\end{enumerate}

Our central finding is that these two questions can have opposite
answers.

The EPGG is useful here because the severity of the free-rider problem
changes over time without direct notification. Communication is
therefore potentially valuable, but not equally so in every regime.

Our contributions are:

\begin{enumerate}[leftmargin=*,nosep]
  \item \textbf{Same-checkpoint continuation controls.} We introduce a clean experimental design for isolating the role of message content during continued learning: fork identical learned checkpoints into learned, random, or silent channel modes and compare downstream outcomes. This separates continued-learning channel-content effects from frozen-endpoint protocol behavior within a fixed architecture and task.
  \item \textbf{Continued-learning benefit vs.\ weak endpoint coherence.} Applying this design in the EPGG case study, we find a clear late-checkpoint continued-learning advantage for learned messages in the mixed-motive regime, while frozen-checkpoint interventions reveal a much weaker endpoint protocol: sender-shuffled messages can outperform natural messages.
  \item \textbf{Strategic value-of-information in mixed regimes.} In this EPGG setting, communication matters most where incentives are mixed rather than fully aligned. In the cooperation-dominant regime, learned message content shows no advantage over silence or simple random channels, and a matched-stat sender-shuffle branch can outperform learned communication.
  \item \textbf{Endpoint causal disaggregation.} Frozen sender-specific token interventions show that endpoint messages are not inert: signed aggregate effects remain near zero while mean absolute sender--receiver effects remain sizeable, indicating substantial local influence despite weak aggregate endpoint effects.
\end{enumerate}

\hypertarget{sec-setup}{%
\section{Setup}\label{sec-setup}}

\hypertarget{extended-public-goods-game-with-regime-switching}{%
\subsection{Extended public goods game with regime
switching}\label{extended-public-goods-game-with-regime-switching}}

We study a four-agent (\(N=4\)) Extended Public Goods Game (EPGG) played
over \(T=100\) rounds per episode. Each round \(t\), agent \(i\)
observes a noisy private signal
\(\fhat_{i,t} = f_t + \varepsilon_{i,t}\), where
\(\varepsilon_{i,t} \sim \mathcal{N}(0, \sigma^2)\) with
\(\sigma = 0.5\), and chooses to cooperate (\(a_i = C\)) or defect
(\(a_i = D\)). Each agent holds an endowment of \(c=4\) units. A
cooperator contributes \(c\) to a shared pool; a defector keeps \(c\) as
private payoff. Contributions are multiplied by the current regime
factor \(f_t\) and split equally, so each agent's round payoff is:
\begin{equation}\protect\hypertarget{eq-payoff}{}{
  u_i = \frac{f_t}{N} \sum_{j=1}^{N} c \cdot \mathbf{1}[a_j = C] \;+\; c \cdot \mathbf{1}[a_i = D]
}\label{eq-payoff}\end{equation} where the first term is agent \(i\)'s
share of the public pool and the second is the private endowment
retained when defecting (zero when cooperating). Throughout, we report
effect sizes in percentage points (pp): a change from 0.40 to 0.53 is
\(+13\pp\).

The hidden multiplier \(f_t\) takes values in
\(\mathcal{F} = \{0.5, 1.5, 2.5, 3.5, 5.0\}\) and switches with
probability \(\rho = 0.05\) per round (geometric holding time
\({\sim}20\) rounds). Each agent's action is subject to trembling: with
probability \(\varepsilon_{\text{tremble}} = 0.05\), the action is
replaced by a uniform random choice, modeling execution noise.

When \(f < N = 4\), defection is the dominant strategy; when \(f > N\),
cooperation dominates regardless of others' actions. The mixed-motive
regime (\(f = 3.5\)) is the critical case: cooperation is collectively
beneficial but individually costly (\(f/N = 0.875 < 1\), so each unit
contributed returns less than one unit to the contributor). Concretely,
a sole defector among three cooperators earns \(14.5\) versus \(14.0\)
for a cooperator at \(f\!=\!3.5\) (a temptation of \(+0.5\) per round),
but earns \(19.0\) versus \(20.0\) at \(f\!=\!5.0\) (a penalty of
\(-1.0\)). This regime creates the strongest demand for communication.
The full multiplier set spans five regimes, but the contrast between
\(f\!=\!3.5\) and \(f\!=\!5.0\) is theoretically central because it
separates ambiguous mixed incentives from a regime where cooperation is
individually optimal. Unless otherwise noted, reported quantities such
as \(\pcoopgiven{f}\) condition on the
\emph{true round-level multiplier} \(f_t\) during evaluation rather than
on an episode-level label.

\hypertarget{communication-channel}{%
\subsection{Communication channel}\label{communication-channel}}

In the communication condition (\texttt{comm\_symm}), agents
simultaneously broadcast a binary message \(m_i \in \{0, 1\}\) before
choosing actions. All agents observe the same sender-indexed message
vector. Messages have no pre-assigned meaning; any semantics must emerge
through learning. In the no-communication condition
(\texttt{no\_comm\_symm}), no messages are exchanged. Agents never
observe the true multiplier \(f_t\), other agents' private signals, or
other agents' rewards.

\hypertarget{training}{%
\subsection{Training}\label{training}}

We train agents using independent PPO \citep{schulman2017proximal} with
generalized advantage estimation \citep{schulman2016high}
(\(\gamma = 0.99\), \(\lambda = 0.95\), clip ratio \(= 0.2\)). Each
agent uses separate two-hidden-layer MLPs (hidden width 64) for the
action policy and value function; sender agents additionally use a
separate two-hidden-layer MLP for the message policy. At each round, a
sender first emits a message from the wrapped Set-A observation
available before same-round message delivery, and all agents then select
actions conditioned on the received same-round message vector. For
sender-updated samples, the action head and message head are optimized
jointly with one clipped objective over \(\log \pi(a_t, m_t)\), using
the agent's own reward return and the same GAE advantage; the shared
value network predicts only that agent's own discounted return. The
policies are not recurrent. Instead, temporal information enters through
a trainer-side observation wrapper that converts the raw environment
observation \([\fhat, \text{endowment}]\) into Set-A inputs
\([\fhat, \text{endowment}, \text{last-round cooperation fraction}, \text{own last action}, \text{EWMA cooperation}]\),
where EWMA denotes an exponential moving average, plus one two-entry
one-hot block per sender when communication is enabled. The base wrapped
observation is therefore 5-dimensional; with four senders and binary
messages, the communication slice adds eight dimensions (two per
sender), giving a 13-dimensional actor input in the communication
condition. At message time this message slice reflects previously
delivered messages (all zeros at episode start), and after delivery the
action policy sees the rebuilt same-round message vector. The value
network receives the same features plus a normalized within-episode time
scalar, giving 14 dimensions by default. During training, each sender's
delivered token is independently corrupted with probability 0.1 by
resampling from that sender's empirical token marginal; this
message-dropout corruption affects online sampled trajectories but not
the frozen-checkpoint perturbation analyses. Agents therefore track the
sticky latent regime only through current noisy signals, these simple
lagged summaries, and communication available through the wrapped
observation. Key design choices:

\textbf{Why independent PPO.} As argued in the introduction, we use
independent PPO to keep the attribution problem in the decentralized
regime rather than partly resolving it through centralized training
signals.

\textbf{Entropy annealing.} Both action and message entropy coefficients
decay linearly over training: action entropy from \(0.01 \to 0.001\),
message entropy from \(0.01 \to 0.0\). This allows early exploration
while permitting conventions to crystallize. The learning rate follows a
cosine schedule from \(3 \times 10^{-4}\) to \(10^{-5}\).

\textbf{Seeds.} Fifteen independent seeds per condition, trained for
150k episodes with checkpoints at 50k, 100k, and 150k.

\hypertarget{sec-eval}{%
\subsection{Evaluation suite}\label{sec-eval}}

All evaluation uses greedy action selection (argmax policy) to isolate
learned behavior from exploration noise. These greedy checkpoint
evaluations are our main evidence about policy quality over training. By
contrast, the dense online training curves introduced later are
descriptive context only: they summarize sampled on-policy behavior
during training and therefore still reflect tremble noise, message
dropout, and residual exploration. Unless otherwise noted, means, SEMs,
bootstrap confidence intervals, and sign-flip tests treat training seed
as the unit of analysis; paired tests operate on per-seed paired deltas.
We evaluate four diagnostic dimensions:

\textbf{Message interventions.} At each checkpoint, we freeze the policy
and replay episodes while tampering with the messages agents receive.
The interventions test different hypotheses about what matters in the
message stream:

\begin{itemize}[leftmargin=*,nosep]
  \item \texttt{zeros}: zero the entire message slice of the wrapped observation after message construction---tests whether the policy benefits from \emph{any} message input.
  \item \texttt{fixed0}: replace every sender slot with token~0 before one-hot encoding---tests a constant but non-empty message pattern.
  \item \texttt{indep\_random}: replace sender slots with independent random bits each round---tests whether slot-wise noise is enough.
  \item \texttt{public\_random}: replace all sender slots with the same random bit each round---tests whether a shared coordination cue suffices.
  \item \texttt{sender\_shuffle}: for each sender, replace the current token with one drawn from that sender's empirical token pool---preserving per-sender marginal token frequency while breaking alignment with current state and time.
  \item \texttt{permute\_slots}: randomly permute sender slots each round while preserving the delivered bits---tests whether receivers track \emph{who} sent a message.
\end{itemize}

These frozen-checkpoint perturbations estimate the effect of specific
endpoint message manipulations; they do not, by themselves, identify the
full causal value of communication over training.

\textbf{Channel controls.} We compare four channel modes during
\emph{continued training} from the same learned 50k checkpoint:
\texttt{learned} (sender's actual message), \texttt{always\_zero} (all
sender slots forced to token\textasciitilde0), \texttt{indep\_random}
(sender slots randomized independently each round), and
\texttt{public\_random} (all sender slots share the same random bit each
round). This tests whether message \emph{content} matters for continued
learning once initialization is held fixed.

\textbf{Sender and receiver semantics.} Appendix\textasciitilde C
summarizes sender message rates and receiver cooperation by discretizing
each agent's noisy private signal into five bins and conditioning on
sender identity. The full bin definitions and notation appear there.

\textbf{Sender-specific causal endpoint probe.} At the frozen 150k
endpoint, we take greedy-evaluation states from the natural rollout,
hold the raw observations and all other message slots fixed, force
sender \(i\)'s token to 0 or 1, and measure the induced change in
receiver \(j\)'s cooperation probability and greedy action. Unlike the
receiver-semantics summaries, this is an interventional test of whether
sender-conditioned endpoint effects are causally used by the frozen
policy.

These diagnostics answer different questions. Same-checkpoint
continuation isolates whether channel content affects
\emph{continued learning} when initialization is fixed. Frozen message
interventions ask whether the \emph{endpoint policy} benefits from the
natural online message stream. Sender-specific frozen interventions ask
whether individual sender tokens retain local causal influence at the
endpoint. Receiver-semantics analyses are descriptive rather than causal
and are included to show how aggregate endpoint summaries can hide
sender-conditioned structure.

\textbf{Roadmap.} The remaining sections are organized as follows. The
\protect\hyperlink{sec-main-result}{baseline comparison} establishes a
descriptive baseline by comparing separately trained communication and
no-communication policies. The
\protect\hyperlink{sec-semantic-window}{continued-learning analysis}
presents the paper's core identification design:
\protect\hyperlink{sec-sameckpt}{same-checkpoint continuation} and
\protect\hyperlink{sec-frozen-endpoint}{frozen-checkpoint endpoint
interventions}. The \protect\hyperlink{sec-discussion}{Discussion} then
places the results in context and discusses limitations, while
Appendices\textasciitilde C--D provide complementary endpoint and
mechanism diagnostics.

\hypertarget{sec-main-result}{%
\section{Baseline communication gap in separately trained
policies}\label{sec-main-result}}

\begin{table}[H]
  \caption{Round-conditional cooperation rates $P(C \mid f_t=f)$ for communication vs.\ no-communication conditions across training. Mean $\pm$ SEM over 15 seeds. The final row reports the paired mean gap (\texttt{comm\_symm} minus \texttt{no\_comm\_symm}).}
  \tablabel{comm_gap}
  \centering
  \small
  \begin{tabular}{llccc}
    \toprule
    & & \multicolumn{3}{c}{Checkpoint (episodes)} \\
    \cmidrule(lr){3-5}
    $f$ regime & Condition & 50k & 100k & 150k \\
    \midrule
    \multirow{3}{*}{$f\!=\!3.5$}
      & \texttt{comm\_symm}     & $\TIcommTFFk$ & $\TIcommTFHk$ & $\TIcommTFOfk$ \\
      & \texttt{no\_comm\_symm} & $\TIncTFFk$ & $\TIncTFHk$ & $\TIncTFOfk$ \\
      & $\commgap$              & $\TIgapTFFk$ & $\TIgapTFHk$ & $\TIgapTFOfk$ \\
    \midrule
    \multirow{3}{*}{$f\!=\!5.0$}
      & \texttt{comm\_symm}     & $\TIcommFVFk$ & $\TIcommFVHk$ & $\TIcommFVOfk$ \\
      & \texttt{no\_comm\_symm} & $\TIncFVFk$ & $\TIncFVHk$ & $\TIncFVOfk$ \\
      & $\commgap$              & $\TIgapFVFk$ & $\TIgapFVHk$ & $\TIgapFVOfk$ \\
    \bottomrule
  \end{tabular}
\end{table}

We begin with a separately trained baseline comparison. Because the
communication and no-communication policies are trained independently,
the gap in Table \ref{tab:comm_gap} mixes message effects with broader
training-trajectory differences; we use it to motivate the tighter
same-checkpoint analysis below. Figure~\ref{fig-value-surface} later
shows that this descriptive gap peaks in the upper mixed regimes rather
than increasing monotonically with generic ``difficulty.'\,'

At \(f = 3.5\) (mixed regime), communication produces a robust
\(+\pvGapTFFkPP\pp\) cooperation advantage at 50k episodes, with all 15
seeds showing positive effects (range: \(+\pvGapRangeLo\) to
\(+\pvGapRangeHi\pp\)). This benefit persists more modestly at 150k
(\(+\pvGapTFOfkPP\pp\), \(\pvNposOfk\)/15 seeds positive).

At \(f = 5.0\) (cooperation-dominant regime), the communication
advantage is small at 50k (\(+\pvGapFVFkPP\pp\)) and reverses by 150k
(\(\pvGapFVOfkPP\pp\), \(p < 0.001\)). Appendix\textasciitilde D weighs
more strongly against a pure architecture-slowing account and toward
late mixed-regime conditioning: communication is not behind early at
\(f\!=\!5.0\), history interventions matter more than message corruption
at 150k, and same-checkpoint controls show no learned-content advantage
there.

Communication helps most where latent-state information matters under
mixed incentives, and the \(f\!=\!3.5\) benefit declines from 50k to
150k without disappearing entirely.

\hypertarget{sec-semantic-window}{%
\section{When does message content matter?}\label{sec-semantic-window}}

The communication benefit raises a question: does message \emph{content}
drive the cooperation advantage, or does merely having a channel (even a
noisy one) suffice? We address this with a sequence of controls centered
on same-checkpoint continuation.

\hypertarget{sec-sameckpt}{%
\subsection{Same-checkpoint continuation isolates continued-training
channel-content effects}\label{sec-sameckpt}}

The separately trained comparison in Table \ref{tab:comm_gap} confounds
message effects with everything else that differs between training runs.
To remove that confound, we hold the starting point fixed: all branches
begin from the \textbf{same} learned 50k checkpoints. We then fork those
checkpoints into four basic channel controls plus one matched-stat
continuation control (\(N = 15\) seeds).

\begin{table}[H]
  \caption{Same-checkpoint continuation controls: cooperation when all modes start from identical learned 50k policies. At 50k, all values are identical (same checkpoint). By 150k, the mixed-motive branch ($f\!=\!3.5$) retains a clear learned-channel advantage, whereas the cooperation-dominant regime ($f\!=\!5.0$) shows little separation. The matched-stat \texttt{sender\_shuffle} row preserves per-sender token frequencies while breaking state-contingency. Mean $\pm$ SEM over \TIIInSeeds{} seeds; $\Delta$ column shows the paired learned$-$control gap at 150k with 95\% bootstrap CI.}
  \tablabel{sameckpt}
  \centering
  \small
  \begin{tabular}{lccccc}
    \toprule
    & \multicolumn{2}{c}{$f\!=\!3.5$} & \multicolumn{2}{c}{$f\!=\!5.0$} & \\
    \cmidrule(lr){2-3} \cmidrule(lr){4-5}
    Channel mode & 50k & 150k & 50k & 150k & $\Delta$ at 150k ($f\!=\!3.5$) \\
    \midrule
    \texttt{learned}        & $\TIIILearnedFk$ & $\mathbf{\TIIILearnedOfk}$ & $\TIIILearnedFkFV$ & $\TIIILearnedOfkFV$ & --- \\
    \texttt{indep\_random}  & $\TIIIIndepFk$ & $\TIIIIndepOfk$ & $\TIIIIndepFkFV$ & $\TIIIIndepOfkFV$ & $\TIIIIndepGapOfk\pp\;\TIIIIndepGapOfkCI$ \\
    \texttt{public\_random} & $\TIIIPubFk$ & $\TIIIPubOfk$ & $\TIIIPubFkFV$ & $\TIIIPubOfkFV$ & $\TIIIPubGapOfk\pp\;\TIIIPubGapOfkCI$ \\
    \texttt{always\_zero}   & $\TIIIZeroFk$ & $\TIIIZeroOfk$ & $\TIIIZeroFkFV$ & $\TIIIZeroOfkFV$ & $\TIIIZeroGapOfk\pp\;\TIIIZeroGapOfkCI$ \\
    \midrule
    \texttt{sender\_shuffle} & $\TIIILearnedFk$ & $\TSSshufCoopTFOfkPM$ & $\TIIILearnedFkFV$ & $\TSSshufCoopFVOfkPM$ & $\TSSgapTFOfk\pp\;\TSSgapTFOfkCI$ \\
    \bottomrule
  \end{tabular}
\end{table}

Table \ref{tab:sameckpt} therefore speaks to continued-training effects
rather than a full-run decomposition. By 150k at \(f\!=\!3.5\), learned
messages retain paired advantages of \(\TIIIZeroGapOfk\pp\) versus
silence (95\% CI \(\TIIIZeroGapOfkCI\), sign-flip
\(p\TIIIZeroGapOfkP\)), \(\TIIIPubGapOfk\pp\) versus public random (CI
\(\TIIIPubGapOfkCI\), \(p\TIIIPubGapOfkP\)), and \(\TIIIIndepGapOfk\pp\)
versus independent random (CI \(\TIIIIndepGapOfkCI\),
\(p\TIIIIndepGapOfkP\)). All three paired confidence intervals exclude
zero, but all branches decline from the shared 50k starting point: the
learned branch does not \emph{sustain} cooperation, it \emph{slows} the
decline relative to the controls. A natural concern is
channel-distribution shift: the learned-minus-control gap may partly
reflect adaptation cost from receiving unfamiliar inputs rather than
semantic value. The matched-stat \texttt{sender\_shuffle} continuation
addresses this by replacing each sender's token with a draw from that
sender's empirical marginal, preserving on-distribution marginals while
destroying state-contingency. If learned still outperforms
sender-shuffle, the advantage is harder to attribute to distribution
matching alone. At 150k and \(f\!=\!3.5\), learned still exceeds
sender-shuffle on average (53.6\% vs.~44.6\% cooperation; \(+9.0\pp\)
mean paired gap), but this gap is heterogeneous and its bootstrap CI
overlaps zero; at \(f\!=\!5.0\), sender-shuffle instead outperforms
learned by \(15.9\pp\). The cleanest interpretation is therefore
intermediate: the learned-vs-zero/random advantage combines genuine
state-linked message value with broader channel dependence, and the
semantic component is real but more modest under matched-stat controls.

Figure~\ref{fig-value-surface} makes the multiplier-wide version of this
point visible before we turn to the endpoint intervention suite.

\begin{figure}[t]

{\centering \includegraphics{main_files/figure-pdf/fig-value-surface-output-1.pdf}

}

\caption{\label{fig-value-surface}Full multiplier surface for three key
150k contrasts. Left: separately trained communication minus
no-communication endpoint gap. Middle: same-checkpoint learned minus
silence continuation gap. Right: frozen natural minus sender-shuffle
endpoint gap. The continued-learning content effect peaks in the upper
mixed regimes (\(f\!=\!2.5, 3.5\)), while the raw endpoint gap reverses
at \(f\!=\!5.0\) and sender-shuffling is most harmful to the natural
endpoint protocol at \(f\!=\!2.5, 3.5\).}

\end{figure}

\begin{figure}[t]

{\centering \includegraphics{main_files/figure-pdf/fig-semantic-window-output-1.pdf}

}

\caption{\label{fig-semantic-window}Same-checkpoint continuation
controls at 150k episodes (15 seeds). \textbf{Left:} Paired
learned\(-\)control deltas at \(f\!=\!3.5\) for each seed.
\textbf{Right:} Raw per-seed cooperation at \(f\!=\!5.0\) across the
four channel modes. Black squares show mean \(\pm\) SEM.}

\end{figure}

\hypertarget{sec-frozen-endpoint}{%
\subsection{Frozen-checkpoint endpoint use is mixed and non-robust at
150k}\label{sec-frozen-endpoint}}

The preceding experiment shows that message content matters for
\emph{learning}. We now ask a different question: does the
\emph{already-trained} policy still benefit from natural messages during
evaluation, with no further learning? The answer is much weaker.

\begin{table}[H]
  \caption[Frozen-checkpoint intervention effects at $f\!=\!3.5$ and 150k.]{Frozen-checkpoint intervention effects in the mixed-motive regime ($f\!=\!3.5$) at the 150k checkpoint. $\Delta P(C)$ in percentage points, computed as natural $-$ intervened: positive values mean natural messages helped, negative values mean the intervention \emph{outperformed} natural messages. Mean $\pm$ SEM over 15 seeds; 95\% bootstrap CI and sign consistency (fraction of seeds where natural $>$ intervention) are reported for 150k only. The corresponding 50k endpoint summaries appear in Appendix~C.}
  \tablabel{frozen_endpoint}
  \centering
  \small
  \begin{tabular}{lccl}
    \toprule
    Intervention & 150k & 95\% CI & Sign \\
    \midrule
    \texttt{zeros}          & $\TFRZerosOfk \pm \TFRZerosOfkSEM$ & $\TFRZerosOfkCI$ & $\TFRZerosOfkSign$ \\
    \texttt{fixed0}         & $\TFRFixZeroOfk \pm \TFRFixZeroOfkSEM$ & $\TFRFixZeroOfkCI$ & $\TFRFixZeroOfkSign$ \\
    \texttt{public\_random} & $\TFRPubOfk \pm \TFRPubOfkSEM$ & $\TFRPubOfkCI$ & $\TFRPubOfkSign$ \\
    \texttt{indep\_random}  & $\TFRIndepOfk \pm \TFRIndepOfkSEM$ & $\TFRIndepOfkCI$ & $\TFRIndepOfkSign$ \\
    \texttt{sender\_shuffle} & $\TFRShuffleOfk \pm \TFRShuffleOfkSEM$ & $\TFRShuffleOfkCI$ & $\TFRShuffleOfkSign$ \\
    \texttt{permute\_slots} & $\TFRPermuteOfk \pm \TFRPermuteOfkSEM$ & $\TFRPermuteOfkCI$ & $\TFRPermuteOfkSign$ \\
    \bottomrule
  \end{tabular}
\end{table}

Table \ref{tab:frozen_endpoint} shows that 150k endpoint intervention
effects are modest relative to the same-checkpoint continuation gaps.
The corresponding 50k endpoint summaries are reported in
Appendix\textasciitilde C and are also small in aggregate. The main
exception is \texttt{sender\_shuffle}, which \emph{outperforms} natural
messages at 150k (\(\TFRShuffleOfk\pp\); 95\% CI
\(\TFRShuffleOfkCI\pp\); sign-flip \(p\TFRShuffleOfkP\)). Because
sender-shuffling preserves each sender's marginal token frequency while
breaking state-contingency, this result implies that the frozen endpoint
policy does not robustly benefit from the original state-conditioned
message stream. But are individual messages still doing \emph{anything}?
To test this, we next intervene on one sender token at a time while
holding the rest of the message vector fixed, in the spirit of
intervention-based influence analyses \citep{jaques2019social}.

\begin{table}[H]
  \caption{Frozen sender-specific causal probe at 150k, non-self sender--receiver pairs only. For each true multiplier $f$, we hold the raw observation and other message slots fixed, force sender $i$'s token to 0 or 1, and compute the resulting signed and absolute change in receiver cooperation probability. Flip-rate columns report the fraction of states in which forcing token 0 or 1 changes receiver $j$'s greedy action relative to the natural message. Effect summaries include 95\% bootstrap CIs over training seeds.}
  \tablabel{sender_causal}
  \centering
  \small
  \begin{tabular}{lcccc}
    \toprule
    $f$ & Signed $\Delta P(C)$ (pp) & Mean $|\Delta P(C)|$ (pp) & Flip rate force0 (\%) & Flip rate force1 (\%) \\
    \midrule
    $0.5$ & $\TSCDeltaZeroFive\;\TSCDeltaZeroFiveCI$ & $\TSCAbsZeroFive\;\TSCAbsZeroFiveCI$ & $\TSCFlipZeroZeroFive$ & $\TSCFlipOneZeroFive$ \\
    $1.5$ & $\TSCDeltaOneFive\;\TSCDeltaOneFiveCI$ & $\TSCAbsOneFive\;\TSCAbsOneFiveCI$ & $\TSCFlipZeroOneFive$ & $\TSCFlipOneOneFive$ \\
    $2.5$ & $\TSCDeltaTwoFive\;\TSCDeltaTwoFiveCI$ & $\TSCAbsTwoFive\;\TSCAbsTwoFiveCI$ & $\TSCFlipZeroTwoFive$ & $\TSCFlipOneTwoFive$ \\
    $3.5$ & $\TSCDeltaThreeFive\;\TSCDeltaThreeFiveCI$ & $\TSCAbsThreeFive\;\TSCAbsThreeFiveCI$ & $\TSCFlipZeroThreeFive$ & $\TSCFlipOneThreeFive$ \\
    $5.0$ & $\TSCDeltaFiveZero\;\TSCDeltaFiveZeroCI$ & $\TSCAbsFiveZero\;\TSCAbsFiveZeroCI$ & $\TSCFlipZeroFiveZero$ & $\TSCFlipOneFiveZero$ \\
    \bottomrule
  \end{tabular}
\end{table}

Table \ref{tab:sender_causal} answers the local endpoint question
directly: individual messages still exert local causal effects. For
non-self sender--receiver pairs, forcing a single sender's token flips
the receiver's greedy action
\(\TSCFlipZeroThreeFive\)--\(\TSCFlipOneThreeFive\)\% of the time at
\(f\!=\!3.5\), with mean absolute cooperation effects of
\(\TSCAbsThreeFive\pp\); at \(f\!=\!5.0\), the corresponding values are
\(\TSCFlipZeroFiveZero\)--\(\TSCFlipOneFiveZero\)\% and
\(\TSCAbsFiveZero\pp\). Yet the signed mean effect is near zero at every
multiplier, including \(\TSCDeltaThreeFive\pp\) at \(f\!=\!3.5\) and
\(\TSCDeltaFiveZero\pp\) at \(f\!=\!5.0\). The endpoint channel
therefore has real local causal effects that largely cancel in
aggregate. This pattern is consistent with different senders developing
opposite conventions: one sender's token\textasciitilde1 encourages
cooperation while another's discourages it, so the per-sender effects
wash out when averaged together.

Non-self effects are nearly as large as self effects
(Appendix\textasciitilde C), so the endpoint channel is not merely a
self-conditioning device.

\hypertarget{synthesis-separating-continued-learning-from-endpoint-effects}{%
\subsection{Synthesis: separating continued-learning from endpoint
effects}\label{synthesis-separating-continued-learning-from-endpoint-effects}}

Same-checkpoint continuation and frozen-endpoint interventions answer
different questions. In this EPGG case study:

\begin{enumerate}[leftmargin=*,nosep]
  \item \textbf{Continued-learning value survives in the mixed-motive regime, but weakens under matched-stat controls.} At $f\!=\!3.5$, learned messages outperform all control modes at 150k (Table \ref{tab:sameckpt}). A matched-stat sender-shuffle branch narrows that gap substantially and leaves its CI overlapping zero, indicating that the strongest learned-vs-control separation reflects a mixture of state-linked message value and broader channel dependence rather than a purely semantic channel.
  \item \textbf{Endpoint online use is much weaker and can be adverse.} The frozen-endpoint interventions are small relative to the same-checkpoint gaps, and \texttt{sender\_shuffle} improves performance. Yet the sender-specific causal probe still finds $\TSCAbsThreeFive\pp$ mean absolute non-self effects at $f\!=\!3.5$ despite a signed average near zero. Endpoint communication is therefore locally causal but not organized into a robust shared protocol. This is \emph{aggregate cancellation}: sender-indexed conventions with opposing polarities produce near-zero aggregate effects despite strong per-sender responses.
  \item \textbf{The $f\!=\!5.0$ reversal reflects late history-conditioned miscalibration.} The communication branch drifts downward from 50k to 150k in both regimes, but only $f\!=\!5.0$ turns this drift into a reversal: at $f\!=\!3.5$, learned messages still beat the control modes, whereas at $f\!=\!5.0$ same-checkpoint controls show no learned-content advantage and matched-stat sender-shuffling outperforms learned communication. Appendix~D further shows that the late $f\!=\!5.0$ shortfall is more sensitive to temporal-history interventions than to message corruption, consistent with a failure to disengage mixed-regime conditionality. This is a \emph{strategic value-of-information} failure: evaluating only at $f\!=\!5.0$ would miss the genuine content effect at $f\!=\!3.5$.
\end{enumerate}

Aggregate endpoint summaries can still miss sender-conditioned structure
because opposing per-sender effects cancel in the mean.
Appendix\textasciitilde C reports that observational disaggregation and
polarity analysis; the main identification rests on the paired
continuation controls and frozen causal probes above.

\hypertarget{sec-discussion}{%
\section{Discussion}\label{sec-discussion}}

The preceding results establish a dissociation between
continued-learning value and endpoint protocol coherence. In this EPGG
case study, messages still change learning in the mixed regime even when
the final endpoint code is brittle and sender-indexed, underscoring that
endpoint summaries alone can misstate communication benefit under
independent learning
\citep{papoudakis2019dealing, oroojlooyjadid2022review}.

The results remain conditional on one game, a binary vocabulary, four
fixed-team agents with sender-labeled slots, and independent PPO. The
same-checkpoint design holds initialization fixed but does not fully
remove channel-distribution shift, and our matched-stat sender-shuffle
control still preserves only per-sender marginals rather than richer
temporal structure or a clean self-versus-other decomposition. The
continuation branches are warm starts rather than bitwise uninterrupted
runs, and all frozen evaluations use a fixed evaluation seed (9001), so
uncertainty is over training seeds rather than evaluator-seed sweeps.
The most immediate next step is a stricter matched-history continuation
design that also separates self-versus-other dependence and uses earlier
or multiple branch points.

\hypertarget{references}{%
\subsection*{References}\label{references}}
\addcontentsline{toc}{subsection}{References}

\renewcommand{\bibsection}{}
\bibliography{refs.bib}

\appendix

\clearpage

\hypertarget{sec-app-params}{%
\section{Appendix A: Full experimental
parameters}\label{sec-app-params}}

\begin{table}[H]
  \caption{Complete hyperparameter specification for all training runs.}
  \tablabel{hyperparams}
  \centering
  \small
  \begin{tabular}{ll}
    \toprule
    Parameter & Value \\
    \midrule
    \multicolumn{2}{l}{\textit{Environment}} \\
    Number of agents $N$ & 4 \\
    Episode length $T$ & 100 rounds \\
    Multiplier set $\mathcal{F}$ & $\{0.5, 1.5, 2.5, 3.5, 5.0\}$ \\
    Regime switch probability $\rho$ & 0.05 \\
    Signal noise $\sigma$ & 0.5 (per agent) \\
    Tremble probability $\varepsilon_{\text{tremble}}$ & 0.05 \\
    Endowment $c$ & 4 \\
    \midrule
    \multicolumn{2}{l}{\textit{Architecture}} \\
    Policy/value networks & Each agent: separate 2-layer MLPs for action and value; sender agents additionally have a separate 2-layer message MLP \\
    Hidden size / activation & 64 / ReLU \\
    Recurrent state & None \\
    Observation wrapper & $[\fhat,\ \text{endowment},\ \text{last coop. frac.},\ \text{own last action},\ \text{EWMA coop.},\ \text{received one-hot messages}]$ \\
    Actor input dim. (\texttt{comm\_symm}) & 13 (5 wrapped base features + 8 message features) \\
    Value input dim. (\texttt{comm\_symm}) & 14 (actor input + normalized within-episode time) \\
    Vocabulary size $|M|$ & 2 (binary) \\
    Parameters per network & ${\sim}5$K scale \\
    \midrule
    \multicolumn{2}{l}{\textit{PPO}} \\
    Discount $\gamma$ & 0.99 \\
    GAE $\lambda$ & 0.95 \\
    Clip ratio & 0.2 \\
    Reward scale & 20.0 \\
    \midrule
    \multicolumn{2}{l}{\textit{Schedules}} \\
    Learning rate & $3 \times 10^{-4} \to 10^{-5}$ (cosine) \\
    Action entropy coeff. & $0.01 \to 0.001$ (linear) \\
    Message entropy coeff. & $0.01 \to 0.0$ (linear) \\
    Optimizer & Adam, one optimizer per agent over all trainable parameters \\
    \midrule
    \multicolumn{2}{l}{\textit{Training}} \\
    Total episodes & 150,000 \\
    Seeds & 15 independent seeds \\
    Checkpoint interval & 50,000 episodes \\
    Message dropout & 0.1 per sender per round; dropped token resampled from sender empirical marginal \\
    \midrule
    \multicolumn{2}{l}{\textit{Evaluation}} \\
    Action selection & Greedy (argmax) \\
    Evaluation episodes & 300 per (checkpoint, seed, condition) \\
    Evaluation seed & 9001 (fixed) \\
    \bottomrule
  \end{tabular}
\end{table}

\hypertarget{sec-app-per-seed}{%
\section{Appendix B: Per-seed breakdown of main
results}\label{sec-app-per-seed}}

\begin{table}[H]
  \caption{Summary statistics for cooperation rates and communication gap at $f\!=\!3.5$ across training ($n = \pvPSnSeedsFk$ seeds).}
  \tablabel{per_seed_summary}
  \centering
  \small
  \begin{tabular}{llccc}
    \toprule
    & & \multicolumn{3}{c}{Checkpoint (episodes)} \\
    \cmidrule(lr){3-5}
    Metric & Statistic & 50k & 100k & 150k \\
    \midrule
    \multirow{3}{*}{Comm $P(C)$}
      & Mean & $\pvPScommMeanFk$ & $\pvPScommMeanHk$ & $\pvPScommMeanOfk$ \\
      & Min & $\pvPScommMinFk$ & $\pvPScommMinHk$ & $\pvPScommMinOfk$ \\
      & Max & $\pvPScommMaxFk$ & $\pvPScommMaxHk$ & $\pvPScommMaxOfk$ \\
    \midrule
    \multirow{3}{*}{Comm gap $\Delta$}
      & Mean & $\pvPSgapMeanFk$ & $\pvPSgapMeanHk$ & $\pvPSgapMeanOfk$ \\
      & Min & $\pvPSgapMinFk$ & $\pvPSgapMinHk$ & $\pvPSgapMinOfk$ \\
      & Max & $\pvPSgapMaxFk$ & $\pvPSgapMaxHk$ & $\pvPSgapMaxOfk$ \\
    \bottomrule
  \end{tabular}
\end{table}

\hypertarget{sec-app-alignment}{%
\section{Appendix C: Aggregate endpoint metrics and polarity
alignment}\label{sec-app-alignment}}

The frozen sender-specific interventions in the main text show that
endpoint messages can still have heterogeneous local causal effects.
This appendix adds the descriptive complement: aggregate
receiver-semantics summaries can nevertheless look near zero once they
average across senders.

\textbf{Important caveat.} The receiver-semantics effects reported here
are \emph{observational} (conditioned on sender identity), not
interventional. They describe sender-conditioned structure but do not
isolate a causal mechanism.

For the sender- and receiver-semantics summaries in this appendix, we
discretize each agent's noisy private signal into five bins, denoted
\(\fhat_{\text{bin}}\): \(\fhat < 1.5\) (low), \(1.5 \le \fhat < 2.5\),
\(2.5 \le \fhat < 3.5\), \(3.5 \le \fhat < 4.5\), and \(\fhat \ge 4.5\)
(high). We then summarize \(P(m_i = 1 \mid \fhat_{\text{bin}})\) and
\(P(a_j = C \mid m_i, \fhat_{\text{bin}})\) by sender identity. When we
refer to low and high bins for polarity, we mean \(\fhat < 1.5\) and
\(\fhat \ge 4.5\), respectively.

\hypertarget{early-frozen-endpoint-summaries}{%
\subsection{Early frozen-endpoint
summaries}\label{early-frozen-endpoint-summaries}}

For completeness, Table \ref{tab:frozen_endpoint_50k} reports the frozen
endpoint intervention effects at 50k for the same mixed-motive regime
shown in the main text. These early endpoint effects are already small
in aggregate, which is why the main text focuses Table
\ref{tab:frozen_endpoint} on the final 150k checkpoint.

\begin{table}[H]
  \caption{Frozen-checkpoint intervention effects in the mixed-motive regime ($f\!=\!3.5$) at the 50k checkpoint. $\Delta P(C)$ is computed as natural $-$ intervened, so positive values mean natural messages helped and negative values mean the intervention outperformed natural messages. Mean $\pm$ SEM over 15 seeds.}
  \tablabel{frozen_endpoint_50k}
  \centering
  \small
  \begin{tabular}{lc}
    \toprule
    Intervention & 50k \\
    \midrule
    \texttt{zeros}           & $\TFRZerosFk \pm \TFRZerosFkSEM$ \\
    \texttt{fixed0}          & $\TFRFixZeroFk \pm \TFRFixZeroFkSEM$ \\
    \texttt{public\_random}  & $\TFRPubFk \pm \TFRPubFkSEM$ \\
    \texttt{indep\_random}   & $\TFRIndepFk \pm \TFRIndepFkSEM$ \\
    \texttt{sender\_shuffle} & $\TFRShuffleFk \pm \TFRShuffleFkSEM$ \\
    \texttt{permute\_slots}  & $\TFRPermuteFk \pm \TFRPermuteFkSEM$ \\
    \bottomrule
  \end{tabular}
\end{table}

For completeness on self-conditioning, the 150k frozen sender-causal
probe also shows that self-pair effects are only modestly larger than
non-self effects: mean absolute self-pair effects are
\(\TSCAbsSelfThreeFive\pp\) at \(f\!=\!3.5\) and
\(\TSCAbsSelfFiveZero\pp\) at \(f\!=\!5.0\), versus
\(\TSCAbsThreeFive\pp\) and \(\TSCAbsFiveZero\pp\) for non-self pairs in
the main text. The endpoint channel is therefore not merely a private
memory device.

\hypertarget{per-sender-disaggregation-reveals-hidden-structure}{%
\subsection{Per-sender disaggregation reveals hidden
structure}\label{per-sender-disaggregation-reveals-hidden-structure}}

For each receiver \(j\) and sender \(i\), we compute the per-sender
token effect within observation bins:
\begin{equation}\protect\hypertarget{eq-per-sender}{}{
  \delta_{i \to j}(\fhat_{\mathrm{bin}}) = \pcoopgiven{m_i\!=\!1, \fhat_{\mathrm{bin}}} - \pcoopgiven{m_i\!=\!0, \fhat_{\mathrm{bin}}}
}\label{eq-per-sender}\end{equation} and compare it to the aggregate
effect, which pools across all senders:
\begin{equation}\protect\hypertarget{eq-agg}{}{
  \delta_{\text{agg}}(\fhat_{\mathrm{bin}}) = P(C \mid \exists\, k: m_k\!=\!1,\; \fhat_{\mathrm{bin}}) - P(C \mid \forall\, k: m_k\!=\!0,\; \fhat_{\mathrm{bin}})
}\label{eq-agg}\end{equation}

\begin{table}[H]
  \caption{Aggregate versus per-sender token effects across training. Aggregate effects are near zero due to convention cancellation, while sender-conditioned effects (mean $|\delta_{i \to j}|$) remain large. Means with 95\% bootstrap CIs over 15 training seeds.}
  \tablabel{disagg}
  \centering
  \small
  \begin{tabular}{lccc}
    \toprule
    & \multicolumn{3}{c}{Checkpoint (episodes)} \\
    \cmidrule(lr){2-4}
    Metric & 50k & 100k & 150k \\
    \midrule
    Aggregate token effect     & $\TVaggFk\;\TVaggFkCI$ & $\TVaggHk\;\TVaggHkCI$ & $\TVaggOfk\;\TVaggOfkCI$ \\
    Per-sender token effect    & $\TVpsFk\;\TVpsFkCI$ & $\TVpsHk\;\TVpsHkCI$  & $\TVpsOfk\;\TVpsOfkCI$ \\
    Ratio (per-sender / |agg.|)  & $\TVratioFk$ & $\TVratioHk$ & $\TVratioOfk$ \\
    \bottomrule
  \end{tabular}
\end{table}

At 50k, the aggregate token effect is only \(\pvAggFkPP\pp\), while the
per-sender effect is \(\pvPsFkPP\pp\). The same discrepancy persists at
150k: sender-conditioned effects remain large even though the aggregate
summary stays near zero.

\begin{figure}[t]

{\centering \includegraphics{main_files/figure-pdf/fig-disagg-output-1.pdf}

}

\caption{\label{fig-disagg}Aggregate vs.~per-sender token effects across
training. The aggregate effect (signed mean \(\delta\)) is near zero at
all checkpoints due to convention fragmentation. The per-sender effect
(mean \(|\delta_{i \to j}|\)) reveals strong sender-conditioned
responses that aggregate metrics hide.}

\end{figure}

\hypertarget{polarity-alignment-patterns}{%
\subsection{Polarity alignment
patterns}\label{polarity-alignment-patterns}}

The aggregate cancellation occurs because sender-indexed conventions
often adopt opposing polarities. We summarize polarity by the sign of
\(P(m\!=\!1 \mid \fhat \ge 4.5) - P(m\!=\!1 \mid \fhat < 1.5)\).

Across \TVInSeeds{} seeds, alignment trajectories are heterogeneous:
some seeds show stable alignment, while others flip or lose it between
50k and 150k. This confirms that convention formation in
independent-learner MARL is stochastic rather than converging reliably
to one shared code.

\hypertarget{sec-app-f50-mech}{%
\section{\texorpdfstring{Appendix D: Additional diagnostics on the
\(f\!=\!5.0\) reversal
mechanism}{Appendix D: Additional diagnostics on the f\textbackslash!=\textbackslash!5.0 reversal mechanism}}\label{sec-app-f50-mech}}

The main text leaves a narrower question than whether communication is
\texttt{good\textquotesingle{}\textquotesingle{}\ or}bad'\,' in general:
why does the descriptive gap reverse at \(f\!=\!5.0\) by 150k even
though communication remains beneficial at \(f\!=\!3.5\)? Two broad
explanations are plausible: (i) the communication architecture may
simply slow convergence toward individually rational cooperation, or
(ii) training in mixed-motive regimes may induce conditional strategies
that do not fully disengage once the cooperative regime is entered. The
analyses in this appendix are explanatory diagnostics on the completed
15-seed checkpoints rather than a new primary identification design, but
they help distinguish which interpretation is better supported.

\hypertarget{checkpoint-timing-early-parity-late-divergence}{%
\subsection{Checkpoint timing: early parity, late
divergence}\label{checkpoint-timing-early-parity-late-divergence}}

\begin{table}[H]
  \caption{Greedy checkpoint means at $f\!=\!5.0$ for the main communication and no-communication branches. Communication is not behind early; the gap opens only later. Mean cooperation (\%) over 15 seeds.}
  \tablabel{f50_timing}
  \centering
  \small
  \begin{tabular}{lcccc}
    \toprule
    Condition & 25k & 50k & 100k & 150k \\
    \midrule
    \texttt{comm\_symm}     & 62.0 & 76.1 & 55.6 & 56.1 \\
    \texttt{no\_comm\_symm} & 61.7 & 73.2 & 64.9 & 80.0 \\
    \bottomrule
  \end{tabular}
\end{table}

This timing pattern is hard to reconcile with a pure ``communication
architecture is always slower'\,' account. At \(f\!=\!5.0\),
communication is essentially tied with no-communication at 25k and ahead
at 50k; the degradation appears later. The checkpoint-trend summary
makes the same point from another angle: from 50k to 150k, communication
drops by \(20.0\pp\) on average at \(f\!=\!5.0\), whereas
no-communication rises by \(6.8\pp\). Communication also declines over
the same interval at \(f\!=\!3.5\), so the issue is not late instability
unique to the cooperative regime. What needs explaining is why this late
drift produces a reversal at \(f\!=\!5.0\) but not at \(f\!=\!3.5\).

\begin{figure}[H]

{\centering \includegraphics{../../outputs/eval/paper_strengthen/iter9_online_vs_checkpoint_15seeds/online_vs_checkpoint_f35_f50.png}

}

\caption{\label{fig-online-vs-checkpoint}Online training curves with
greedy checkpoint anchors at \(f\!=\!3.5\) and \(f\!=\!5.0\). Solid
curves show sampled on-policy training behavior and therefore remain
descriptive; dotted markers show greedy checkpoint evaluation at 25k,
50k, 100k, and 150k. The vertical line marks the 50k continuation
boundary. The key pattern is early parity and later divergence, not a
uniformly worse communication branch from the start.}

\end{figure}

\hypertarget{same-checkpoint-controls-no-positive-learned-content-effect-at-f5.0}{%
\subsection{\texorpdfstring{Same-checkpoint controls: no positive
learned-content effect at
\(f\!=\!5.0\)}{Same-checkpoint controls: no positive learned-content effect at f\textbackslash!=\textbackslash!5.0}}\label{same-checkpoint-controls-no-positive-learned-content-effect-at-f5.0}}

Within the fixed communication architecture, same-checkpoint
continuation controls already rule out a simple positive learned-content
explanation for the late \(f\!=\!5.0\) behavior. At 150k, the learned
branch reaches 56.1\% cooperation at \(f\!=\!5.0\), compared with 54.4\%
under \texttt{always\_zero}, 61.4\% under \texttt{public\_random}, and
63.1\% under \texttt{indep\_random}. The matched-stat
\texttt{sender\_shuffle} continuation control does better still at
72.0\%. The contrast with \(f\!=\!3.5\) is the key point: there, learned
communication still stays above all of the basic controls. So the
communication policy appears to retain conditional machinery in both
regimes, but only the mixed regime still rewards it at 150k.

\hypertarget{spell-conditioned-endpoint-audit-history-matters-more-than-messages}{%
\subsection{Spell-conditioned endpoint audit: history matters more than
messages}\label{spell-conditioned-endpoint-audit-history-matters-more-than-messages}}

We next examined the final 150k checkpoints under greedy evaluation
while conditioning on spell age since entry into the current
\(f\!=\!5.0\) episode segment. The goal was not to estimate a new causal
effect size, but to ask what kind of intervention most changes the poor
late-\(f\!=\!5.0\) behavior in the communication condition: message
corruption, or perturbations to temporal/history features in the wrapped
observation.

\begin{table}[H]
  \caption{Selected spell-conditioned diagnostics at $f\!=\!5.0$ from the final 150k checkpoints. Entries are mean cooperation (\%) over 15 seeds. ``Switch'' denotes the first round after entering an $f\!=\!5.0$ spell; ``21+'' denotes long cooperative spells.}
  \tablabel{f50_spell_audit}
  \centering
  \small
  \begin{tabular}{lccc}
    \toprule
    Variant & Overall & Switch & 21+ \\
    \midrule
    \texttt{cond1} natural & 55.5 & 72.0 & 50.7 \\
    \texttt{cond2} natural & 80.4 & 64.9 & 80.0 \\
    \midrule
    \texttt{cond1} + \texttt{zeros} & 56.0 & 67.1 & 52.4 \\
    \texttt{cond1} + \texttt{public\_random} & 57.6 & 68.9 & 53.1 \\
    \texttt{cond1} + \texttt{sender\_shuffle} & 57.4 & 72.3 & 52.0 \\
    \midrule
    \texttt{cond1} + \texttt{zero\_ewma} & 79.0 & 80.4 & 77.8 \\
    \texttt{cond1} + \texttt{clamp\_temporal\_low} & 80.0 & 80.8 & 78.7 \\
    \texttt{cond1} + \texttt{clamp\_temporal\_high} & 23.6 & 24.2 & 23.2 \\
    \bottomrule
  \end{tabular}
\end{table}

Three features of Table \ref{tab:f50_spell_audit} are especially
informative.

First, the late-\(f\!=\!5.0\) decay is real and asymmetric across
conditions. In the communication condition, cooperation starts
relatively high immediately after a regime switch (72.0\%) but falls
steadily across longer \(f\!=\!5.0\) spells, reaching 50.7\% in the 21+
bucket. The no-communication condition shows the opposite qualitative
pattern: it starts lower right after the switch (64.9\%) and remains
high in long cooperative spells (80.0\% overall; 80.0\% in the 21+
bucket). This is the pattern expected under a late conditionality or
overwrite account, not under a pure always-slower architecture account.

Second, corrupting the online message stream leaves the decay largely
intact. Replacing natural messages with zeros, public random bits, or
sender-shuffled bits changes the communication-condition mean only
modestly (roughly 56--58\% overall, versus 55.5\% natural), and the
long-spell bucket remains near 52--53\%. So the poor 150k performance at
\(f\!=\!5.0\) is not primarily an endpoint dependence on the exact
online message content.

Third, intervening on temporal/history features changes behavior much
more strongly. Zeroing the EWMA cooperation signal or clamping the
temporal-history proxy low raises \(f\!=\!5.0\) cooperation to about
79--80\%, close to the no-communication level, while clamping that proxy
high collapses cooperation to about 24\%. This indicates that the
problematic late policy is strongly history-conditioned: by 150k, the
communication-trained agents appear to be using temporal or lagged
social features in a way that is maladaptive within long cooperative
spells.

\hypertarget{interpretation-and-scope}{%
\subsection{Interpretation and scope}\label{interpretation-and-scope}}

Taken together, these diagnostics support explanation (ii) more strongly
than explanation (i). The communication branch is not handicapped from
the start; it is competitive or better early at \(f\!=\!5.0\) and only
falls behind later. Same-checkpoint controls then show why this late
drift matters differently across regimes: at \(f\!=\!3.5\), learned
communication still outperforms the basic controls, so conditional
responses retain strategic value, whereas at \(f\!=\!5.0\) the same
learned channel offers no corresponding advantage. Finally, the poor
late-\(f\!=\!5.0\) state is much more sensitive to temporal/history
features than to message corruption. The most coherent reading is
therefore that mixed-regime conditionality remains encoded in the
communication policy and fails to disengage in long cooperative spells.

We do not claim that architecture cost is absent. These diagnostics do
not retrain an exactly capacity-matched no-message architecture under a
continuation protocol, so a contribution from extra inputs or
optimization complexity cannot be ruled out completely. But the current
evidence is more consistent with a late mixed-regime conditioning or
overwrite story than with a purely static architecture-complexity
explanation.

\newpage
\section*{NeurIPS Paper Checklist}

\begin{enumerate}

\item {\bf Claims}
    \item[] Answer: \answerYes{}
    \item[] Justification: The abstract and introduction clearly state four contributions supported by the experimental results in the main body.

\item {\bf Limitations}
    \item[] Answer: \answerYes{}
    \item[] Justification: The \emph{Discussion} section discusses limitations including single game, minimal vocabulary, PPO coupling, and seed heterogeneity.

\item {\bf Theory assumptions and proofs}
    \item[] Answer: \answerNA{}
    \item[] Justification: This is an empirical paper; no theoretical results are presented.

\item {\bf Experimental result reproducibility}
    \item[] Answer: \answerYes{}
    \item[] Justification: Appendix A provides complete hyperparameters. Code will be released upon acceptance.

\item {\bf Open access to data and code}
    \item[] Answer: \answerYes{}
    \item[] Justification: Anonymized code and evaluation scripts will be provided as supplementary material. Full code release upon acceptance.

\item {\bf Experimental setting/details}
    \item[] Answer: \answerYes{}
    \item[] Justification: The \emph{Setup} section and Appendix A provide all training and evaluation details.

\item {\bf Experiment statistical significance}
    \item[] Answer: \answerYes{}
    \item[] Justification: We report mean $\pm$ SEM across 15 seeds, bootstrap confidence intervals (10,000 resamples) for effect sizes, and exact paired sign-flip tests for primary paired comparisons.

\item {\bf Experiments compute resources}
    \item[] Answer: \answerYes{}
    \item[] Justification: Experiments ran on an Apple M1 MacBook Pro (10 cores, 16GB RAM) and an IWR cluster node (quadxeon7). Each 150k-episode training run takes approximately 9 hours. Total compute for all experiments (including pilots, ablations, and the 15-seed expansion) is approximately 1500 CPU-hours.

\item {\bf Code of ethics}
    \item[] Answer: \answerYes{}
    \item[] Justification: This research studies cooperation in abstract game-theoretic settings with no human subjects, sensitive data, or dual-use concerns.

\item {\bf Broader impacts}
    \item[] Answer: \answerNA{}
    \item[] Justification: This is basic research on emergent communication in abstract multi-agent systems. We do not foresee direct negative societal impacts.

\item {\bf Safeguards}
    \item[] Answer: \answerNA{}
    \item[] Justification: No models or datasets with misuse risk are released.

\item {\bf Licenses for existing assets}
    \item[] Answer: \answerNA{}
    \item[] Justification: No pre-existing datasets or models are used. The codebase builds on standard PyTorch.

\item {\bf New assets}
    \item[] Answer: \answerYes{}
    \item[] Justification: We will release the complete codebase (training, evaluation, analysis) and trained checkpoints upon acceptance.

\item {\bf Crowdsourcing and research with human subjects}
    \item[] Answer: \answerNA{}
    \item[] Justification: No human subjects involved.

\item {\bf Institutional review board (IRB) approvals or equivalent for research with human subjects}
    \item[] Answer: \answerNA{}
    \item[] Justification: No human subjects involved.

\item {\bf Declaration of LLM usage}
    \item[] Answer: \answerNA{}
    \item[] Justification: No LLMs are used as part of the core research methodology. LLMs were used only for writing assistance.

\end{enumerate}




\end{document}
