project:
  type: default
  output-dir: _output

format:
  acm-pdf:
    classoption: [manuscript, review, anonymous]
    acm-journal: PACMHCI
    keep-tex: true
    toc: false
    number-sections: true
    colorlinks: true
    cite-method: citeproc
    csl: _extensions/quarto-journals/acm/acm-sigchi-proceedings.csl

bibliography: refs.bib
engine: jupyter
execute:
  echo: false
  warning: false
