project:
  type: default
  output-dir: _output

format:
  pdf:
    documentclass: article
    pdf-engine: xelatex
    keep-tex: true
    toc: false
    number-sections: true
    colorlinks: true
    cite-method: natbib
    biblio-style: plainnat
    template-partials:
      - title.tex
    include-in-header:
      - text: |
          \usepackage{neurips_2025}

bibliography: refs.bib
engine: jupyter
execute:
  echo: false
  warning: false
